project:
  type: website

website:
  title: "Sobreviviendo a la Tesis con R"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: plan.qmd
        text: Plan de trabajo
      - text: Clases
        menu:
          - href: clases/00_manipulacion_datos.qmd
            text: Manipulacion de datos
          - href: clases/01_ejercicios_segmentacion.qmd
            text: Ejercicios Segmentacion
          - href: clases/02_ejercicios_graficos.qmd
            text: Ejercicios Graficos 
          - href: clases/03_workflows.qmd
            text: Workflows
      - href: recursos.qmd
        text: Recursos

format:
  html:
    theme: cosmo
    toc: true



